---
title: "Vota Unicamp!"
author: "Grupo"
output: html_document
---

#Introdução

```{r input, message=FALSE}
Sys.setlocale("LC_TIME")
library(stringr)
library(rvest)
library(googleVis)
library(leaflet)
page = read_html('http://votaunicamp.herokuapp.com/results/', encoding='UTF-8')
tbl = html_table(page)[[2]]
head(tbl)
```

## Formatação de Dados

```{r format, message=FALSE, echo=FALSE, warning=FALSE, results='hide'}
mytbl = data.frame(codigo=as.integer(str_extract(tbl$Curso, "^\\d+")),
                   nivel=NA,
                   curso=gsub("^(\\d+) - (.*)$", "\\2", tbl$Curso),
                   total=tbl$Total,
                   sim=as.integer(str_extract(tbl$Sim, "^\\d+")),
                   nao=as.integer(str_extract(tbl$Não, "^\\d+")),
                   abstencao=as.integer(str_extract(tbl$Abstenções, "^\\d+")))
nivel = str_extract(mytbl$curso, "(Dou|Mes)[a-z]+")
nivel[grepl("Mes", nivel)] = "Mestrado"
nivel[grepl("Dou", nivel)] = "Doutorado"
nivel[is.na(nivel)] = "Graduacao"
mytbl$nivel = nivel
rm(nivel)
mytbl$curso = gsub("(Mes|Dou).+ em (.*)$", "\\2", mytbl$curso)
head(mytbl)
```

## Gauge Plots

```{r plot_gauge}
tbl0 = subset(mytbl, nivel=='Graduacao')
tbl0$pnao = round(tbl0$nao/tbl0$total*100, 0)
gauge = gvisGauge(tbl0[, c('curso', 'pnao')], 'curso', 'nao',
                  options=list(min=0, max=100, greenFrom=0,
                                 greenTo=20, yellowFrom=40, yellowTo=60,
                                 redFrom=80, redTo=100, width=400, height=300))
plot(gauge)
```

## Obtenção de Dados Geográficos

Obter localizações (lat/lon) por meio do OpenStreet Maps:

- Abrir OpenStreet Maps (OSM) em (http://www.openstreetmap.org/#map=16/-22.8173/-47.0677)
- Dar zoom máximo no instituto de interesse
- Olhar o endereço na barra de endereço após o zoom
- Atualizar o data.frame abaixo com as informações

```{r enderecos}
ends = data.frame(instituto=c('IMECC', 'FEM', 'FEF'),
           lat=c(-22.81583,-22.81938,-22.81476),
           lon=c(-47.06769,-47.06592,-47.07333))
map = leaflet()
map = addTiles(map)
map = addCircleMarkers(map, lat=ends$lat, lng=ends$lon, popup = ends$instituto)
map
```

##Proporções

```{r stats, message=FALSE, echo=FALSE, warning=FALSE}
#Proporção de Não
p = with(mytbl, nao/(total))
mes = qnorm(.975)*sqrt(1/(4*mytbl$total))
ics = cbind(pmax(p-mes, 0), pmin(p+mes, 1))
colnames(ics) = c("lower", "upper")
mytbl$p = p
mytbl = cbind(mytbl, ics)
```


```{r message=FALSE, echo=FALSE, warning=FALSE}
#Proporção de Sim
p = with(mytbl, sim/(total))
mes = qnorm(.975)*sqrt(1/(4*mytbl$total))
ics = cbind(pmax(p-mes, 0), pmin(p+mes, 1))
mytbl[,11]=p
mytbl[,12]=ics[,1]
mytbl[,13]=ics[,2]
```


```{r message=FALSE, echo=FALSE, warning=FALSE}
#Proporção de Abstenho
p = with(mytbl, abstencao/(total))
mes = qnorm(.975)*sqrt(1/(4*mytbl$total))
ics = cbind(pmax(p-mes, 0), pmin(p+mes, 1))
mytbl[,14]=p
mytbl[,15]=ics[,1]
mytbl[,16]=ics[,2]
names(mytbl) <- c(names(mytbl)[1:7],"p-nao", "inf-n", "sup-n", "p-sim", "inf-s","sup-s","p-abs", "inf-a", "sup-a")
mytbl[,8:16]=round(mytbl[,8:16],2)

```


## Intervalos de Confiança

```{r stats}
p = with(mytbl, nao/(total))
mes = qnorm(.975)*sqrt(1/(4*mytbl$total))
ics = cbind(pmax(p-mes, 0), pmin(p+mes, 1))
colnames(ics) = c("lower", "upper")
mytbl$p = p
mytbl = cbind(mytbl, ics)
```
